# -*- coding: utf-8 -*-
"""Realestate data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RK0WTKtN1KfR4JD_XGnExHBv9YNQDhWM
"""

import json
import pandas as pd

# -------------------------------
# 1️⃣ Load JSON File
# -------------------------------
with open('/content/drive/MyDrive/Guvi/Dataset/agents_20k.json', 'r') as f:
    data = json.load(f)

# If JSON is a list → convert directly
# If single record → wrap in list
if isinstance(data, dict):
    data = [data]

# -------------------------------
# 2️⃣ Convert to DataFrame
# -------------------------------
df = pd.json_normalize(data)

print("Original Data:")
print(df.head())


# -------------------------------
# 3️⃣ Standardize Column Names
# -------------------------------
df.columns = df.columns.str.lower().str.strip()

# Rename for consistency
df.rename(columns={
    'agent_id': 'agent_id',
    'name': 'agent_name',
    'phone': 'phone',
    'email': 'email'
}, inplace=True)


# -------------------------------
# 4️⃣ Clean Phone Numbers
# -------------------------------
df['phone'] = df['phone'].astype(str)

# Remove spaces
df['phone'] = df['phone'].str.replace(' ', '')

# Keep only numbers + +
df['phone'] = df['phone'].str.replace(r'[^\d+]', '', regex=True)


# -------------------------------
# 5️⃣ Clean Email
# -------------------------------
df['email'] = df['email'].str.lower().str.strip()


# -------------------------------
# 6️⃣ Handle Missing Values
# -------------------------------
df.fillna({
    'agent_name': 'Unknown',
    'phone': 'Not Available',
    'email': 'Not Available'
}, inplace=True)


# -------------------------------
# 7️⃣ Remove Duplicates
# -------------------------------
df.drop_duplicates(subset=['agent_id'], inplace=True)


# -------------------------------
# 8️⃣ Final Output
# -------------------------------
print("\nCleaned Data:")
print(df)

print("\nData Info:")
print(df.info())


# -------------------------------
# 9️⃣ Save Clean Data
# -------------------------------
df.to_csv("cleaned_agents.csv", index=False)

print("\n✅ Agents Data Prepared Successfully!")

import json
import pandas as pd

# -------------------------------
# 1️⃣ Load JSON File
# -------------------------------
with open('/content/drive/MyDrive/Guvi/Dataset/agents_enhanced_20k.json', 'r') as f:
    data = json.load(f)

# Ensure list format
if isinstance(data, dict):
    data = [data]

# -------------------------------
# 2️⃣ Convert to DataFrame
# -------------------------------
df = pd.json_normalize(data)

print("Original Data:")
print(df.head())


# -------------------------------
# 3️⃣ Standardize Column Names
# -------------------------------
df.columns = df.columns.str.lower().str.strip()

# Rename columns properly
df.rename(columns={
    'name': 'agent_name'
}, inplace=True)


# -------------------------------
# 4️⃣ Clean Phone Numbers
# -------------------------------
if 'phone' in df.columns:
    df['phone'] = df['phone'].astype(str)
    df['phone'] = df['phone'].str.replace(' ', '')
    df['phone'] = df['phone'].str.replace(r'[^\\d+]', '', regex=True)


# -------------------------------
# 5️⃣ Clean Email
# -------------------------------
if 'email' in df.columns:
    df['email'] = df['email'].str.lower().str.strip()


# -------------------------------
# 6️⃣ Convert Numeric Fields
# -------------------------------
numeric_cols = [
    'commission_rate',
    'deals_closed',
    'rating',
    'experience_years',
    'avg_closing_days'
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')


# -------------------------------
# 7️⃣ Handle Missing Values
# -------------------------------
df.fillna({
    'agent_name': 'Unknown',
    'phone': 'Not Available',
    'email': 'Not Available',
    'commission_rate': 0,
    'deals_closed': 0,
    'rating': 0,
    'experience_years': 0,
    'avg_closing_days': 0
}, inplace=True)


# -------------------------------
# 8️⃣ Remove Duplicates
# -------------------------------
if 'agent_id' in df.columns:
    df.drop_duplicates(subset=['agent_id'], inplace=True)


# -------------------------------
# 9️⃣ Final Output
# -------------------------------
print("\nCleaned Data:")
print(df.head())

print("\nData Info:")
print(df.info())


# -------------------------------
# 🔟 Save Clean Data
# -------------------------------
df.to_csv("cleaned_agents_enhanced.csv", index=False)

print("\n✅ Agents Data Prepared Successfully!")

import json
import pandas as pd

# -------------------------------
# 1️⃣ Load JSON File
# -------------------------------
with open('/content/drive/MyDrive/Guvi/Dataset/buyers_20k.json', 'r') as f:
    data = json.load(f)

# Ensure list format
if isinstance(data, dict):
    data = [data]

# -------------------------------
# 2️⃣ Convert to DataFrame
# -------------------------------
df = pd.json_normalize(data)

print("Original Data:")
print(df.head())


# -------------------------------
# 3️⃣ Standardize Column Names
# -------------------------------
df.columns = df.columns.str.lower().str.strip()


# -------------------------------
# 4️⃣ Clean Text Fields
# -------------------------------
text_cols = ['buyer_type', 'payment_mode', 'loan_provider']

for col in text_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.lower()


# -------------------------------
# 5️⃣ Convert Boolean Field
# -------------------------------
if 'loan_taken' in df.columns:
    df['loan_taken'] = df['loan_taken'].astype(bool)


# -------------------------------
# 6️⃣ Convert Numeric Fields
# -------------------------------
numeric_cols = ['buyer_id', 'loan_amount']

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')


# -------------------------------
# 7️⃣ Handle Missing Values
# -------------------------------
df.fillna({
    'buyer_type': 'unknown',
    'payment_mode': 'unknown',
    'loan_provider': 'none',
    'loan_amount': 0
}, inplace=True)


# -------------------------------
# 8️⃣ Remove Duplicates
# -------------------------------
if 'buyer_id' in df.columns:
    df.drop_duplicates(subset=['buyer_id'], inplace=True)


# -------------------------------
# 9️⃣ Final Output
# -------------------------------
print("\nCleaned Data:")
print(df.head())

print("\nData Info:")
print(df.info())


# -------------------------------
# 🔟 Save Clean Data
# -------------------------------
df.to_csv("cleaned_buyers.csv", index=False)

print("\n✅ Buyers Data Prepared Successfully!")

import json
import pandas as pd

# -------------------------------
# 1️⃣ Load JSON File
# -------------------------------
with open('/content/drive/MyDrive/Guvi/Dataset/listings_20k.json', 'r') as f:
    data = json.load(f)

# Ensure list format
if isinstance(data, dict):
    data = [data]

# -------------------------------
# 2️⃣ Convert to DataFrame
# -------------------------------
df = pd.json_normalize(data)

print("Original Data:")
print(df.head())


# -------------------------------
# 3️⃣ Standardize Column Names
# -------------------------------
df.columns = df.columns.str.lower().str.strip()

# Rename columns for consistency
df.rename(columns={
    'listing_id': 'listing_id',
    'city': 'location',
    'property_type': 'property_type',
    'price': 'price',
    'sqft': 'area',
    'date_listed': 'date_listed',
    'agent_id': 'agent_id',
    'latitude': 'latitude',
    'longitude': 'longitude'
}, inplace=True)


# -------------------------------
# 4️⃣ Convert Date Format
# -------------------------------
if 'date_listed' in df.columns:
    df['date_listed'] = pd.to_datetime(df['date_listed'], errors='coerce')
    df['date_listed'] = df['date_listed'].dt.strftime('%Y-%m-%d')


# -------------------------------
# 5️⃣ Convert Numeric Fields
# -------------------------------
numeric_cols = ['price', 'area', 'latitude', 'longitude']

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')


# -------------------------------
# 6️⃣ Clean Text Fields
# -------------------------------
if 'location' in df.columns:
    df['location'] = df['location'].str.strip().str.title()

if 'property_type' in df.columns:
    df['property_type'] = df['property_type'].str.strip().str.title()


# -------------------------------
# 7️⃣ Handle Missing Values
# -------------------------------
df.fillna({
    'price': 0,
    'area': 0,
    'location': 'Unknown',
    'property_type': 'Unknown'
}, inplace=True)


# -------------------------------
# 8️⃣ Remove Duplicates
# -------------------------------
if 'listing_id' in df.columns:
    df.drop_duplicates(subset=['listing_id'], inplace=True)


# -------------------------------
# 9️⃣ Final Output
# -------------------------------
print("\nCleaned Data:")
print(df.head())

print("\nData Info:")
print(df.info())


# -------------------------------
# 🔟 Save Clean Data
# -------------------------------
df.to_csv("cleaned_listings.csv", index=False)

print("\n✅ Listings Data Prepared Successfully!")

import json
import pandas as pd

# -------------------------------
# 1️⃣ Load JSON File
# -------------------------------
with open('/content/drive/MyDrive/Guvi/Dataset/property_attributes_20k.json', 'r') as f:
    data = json.load(f)

# Ensure list format
if isinstance(data, dict):
    data = [data]

# -------------------------------
# 2️⃣ Convert to DataFrame
# -------------------------------
df = pd.json_normalize(data)

print("Original Data:")
print(df.head())


# -------------------------------
# 3️⃣ Standardize Column Names
# -------------------------------
df.columns = df.columns.str.lower().str.strip()


# -------------------------------
# 4️⃣ Convert Numeric Fields
# -------------------------------
numeric_cols = [
    'attribute_id',
    'bedrooms',
    'bathrooms',
    'floor_number',
    'total_floors',
    'year_built',
    'tenant_count',
    'metro_distance_km'
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')


# -------------------------------
# 5️⃣ Convert Boolean Fields
# -------------------------------
bool_cols = [
    'is_rented',
    'parking_available',
    'power_backup'
]

for col in bool_cols:
    if col in df.columns:
        df[col] = df[col].astype(bool)


# -------------------------------
# 6️⃣ Clean Text Fields
# -------------------------------
if 'furnishing_status' in df.columns:
    df['furnishing_status'] = df['furnishing_status'].str.strip().str.title()


# -------------------------------
# 7️⃣ Handle Missing Values
# -------------------------------
df.fillna({
    'bedrooms': 0,
    'bathrooms': 0,
    'floor_number': 0,
    'total_floors': 0,
    'year_built': 0,
    'tenant_count': 0,
    'metro_distance_km': 0,
    'furnishing_status': 'Unknown'
}, inplace=True)


# -------------------------------
# 8️⃣ Remove Duplicates
# -------------------------------
if 'attribute_id' in df.columns:
    df.drop_duplicates(subset=['attribute_id'], inplace=True)


# -------------------------------
# 9️⃣ Final Output
# -------------------------------
print("\nCleaned Data:")
print(df.head())

print("\nData Info:")
print(df.info())


# -------------------------------
# 🔟 Save Clean Data
# -------------------------------
df.to_csv("cleaned_property_attributes.csv", index=False)

print("\n✅ Property Attributes Data Prepared Successfully!")

!pip install -q streamlit pandas mysql-connector-python plotly
!wget -q -O cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared.deb

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # 🔹 Load Data
# @st.cache_data
# def load_data():
#     listings_df = pd.read_csv("cleaned_listings.csv")
#     agents_df = pd.read_csv("cleaned_agents.csv")
# 
#     # Merge datasets
#     df = pd.merge(
#         listings_df,
#         agents_df[['agent_id', 'commission_rate']],
#         on='agent_id',
#         how='left'
#     )
# 
#     # Rename columns (SAFE mapping)
#     df.rename(columns={
#         'listing_id': 'Listing_ID',
#         'location': 'Location',
#         'property_type': 'Property_Type',
#         'price': 'Price',
#         'area': 'Sqft',
#         'latitude': 'latitude',
#         'longitude': 'longitude',
#         'commission_rate': 'Commission_Rate'
#     }, inplace=True)
# 
#     # Keep required columns only
#     df = df[['Listing_ID', 'Location', 'Property_Type',
#              'Price', 'Sqft', 'latitude', 'longitude', 'Commission_Rate']]
# 
#     return df
# 
# # Load data
# df = load_data()
# 
# st.title("🏠 Real Estate Dashboard")
# 
# # ✅ 🔹 SIDEBAR FILTERS
# st.sidebar.header("Filter Options")
# 
# location = st.sidebar.multiselect("Select Location", df["Location"].dropna().unique())
# property_type = st.sidebar.multiselect("Property Type", df["Property_Type"].dropna().unique())
# commission_rate = st.sidebar.multiselect("Commission Rate", df["Commission_Rate"].dropna().unique())
# 
# price_range = st.sidebar.slider(
#     "Price Range",
#     int(df["Price"].min()),
#     int(df["Price"].max()),
#     (int(df["Price"].min()), int(df["Price"].max()))
# )
# 
# # 🔹 Apply Filters
# filtered_df = df.copy()
# 
# if location:
#     filtered_df = filtered_df[filtered_df["Location"].isin(location)]
# 
# if property_type:
#     filtered_df = filtered_df[filtered_df["Property_Type"].isin(property_type)]
# 
# if commission_rate:
#     filtered_df = filtered_df[filtered_df["Commission_Rate"].isin(commission_rate)]
# 
# filtered_df = filtered_df[
#     (filtered_df["Price"] >= price_range[0]) &
#     (filtered_df["Price"] <= price_range[1])
# ]
# 
# # ✅ 🔹 SHOW TABLE
# st.subheader("📊 Listings Data")
# st.dataframe(filtered_df, use_container_width=True)
# 
# # ✅ 🔹 BAR CHART
# st.subheader("📈 Average Price by Location")
# if not filtered_df.empty:
#     bar_data = filtered_df.groupby("Location")["Price"].mean().reset_index()
#     fig_bar = px.bar(bar_data, x="Location", y="Price")
#     st.plotly_chart(fig_bar, use_container_width=True)
# else:
#     st.warning("No data available for selected filters")
# 
# # ✅ 🔹 PIE CHART
# st.subheader("🥧 Property Type Distribution")
# if not filtered_df.empty:
#     pie_data = filtered_df["Property_Type"].value_counts().reset_index()
#     pie_data.columns = ["Property_Type", "Count"]
#     fig_pie = px.pie(pie_data, names="Property_Type", values="Count")
#     st.plotly_chart(fig_pie, use_container_width=True)
# 
# # ✅ 🔹 MAP VIEW
# st.subheader("🗺️ Property Locations")
# map_df = filtered_df.dropna(subset=["latitude", "longitude"])
# 
# if not map_df.empty:
#     st.map(map_df[["latitude", "longitude"]])
# else:
#     st.warning("No location data available")
# 
# # ✅ 🔹 TOP 5 EXPENSIVE
# st.subheader("💡 Top 5 Expensive Listings")
# top_df = df.sort_values(by='Price', ascending=False).head(5)
# top_df = top_df[['Listing_ID', 'Location', 'Price']]
# st.table(top_df)

!streamlit run app.py &>/content/logs.txt &

!cloudflared tunnel --url http://localhost:8501